#!/usr/bin/env python3
"""Validate authoritative timing settings and generate deployment-local constants."""
import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'home/admin/smart-enclosure-api/timing.json'


REQUIRED_KEYS = frozenset({
    'sensor_read_interval',
    'sensor_read_timeout',
    'sensor_retry_max',
    'sensor_worker_poll',
    'sensor_worker_stop_timeout',
    'sensor_blocked_retry',
    'sensor_loop_pause',
    'gateway_poll_interval',
    'gateway_retry_max',
    'pi_request_timeout',
    'relay_schedule_check_interval',
    'sensor_stale_after',
    'gateway_stale_after',
    'browser_state_poll_interval',
    'browser_clock_interval',
    'browser_state_stale_after',
    'browser_zones_poll_interval',
    'browser_schedule_confirmation_timeout',
    'browser_request_timeout',
    'browser_history_poll_interval',
    'browser_history_request_timeout',
    'browser_events_poll_interval',
    'browser_events_request_timeout',
    'browser_feeding_poll_interval',
    'browser_feeding_stale_after',
    'history_sample_interval',
})


def validate(document):
    if set(document["settings"]) != REQUIRED_KEYS:
        raise ValueError("Timing setting names must match the supported schema")
    values = {}
    for key, entry in document['settings'].items():
        value = entry['seconds']
        if not key.isidentifier() or not key.islower():
            raise ValueError(f'Invalid setting name: {key}')
        if type(value) not in (int, float) or not math.isfinite(value) or not .001 <= value <= 86400:
            raise ValueError(f'{key}: seconds must be a finite number from 0.001 to 86400')
        if not isinstance(entry['description'], str) or not entry['description'].strip():
            raise ValueError(f'{key}: description is required')
        values[key] = value
    for interval, limit in (
        ('sensor_read_interval', 'sensor_stale_after'),
        ('sensor_read_interval', 'sensor_retry_max'),
        ('gateway_poll_interval', 'gateway_retry_max'),
        ('gateway_poll_interval', 'gateway_stale_after'),
        ('browser_state_poll_interval', 'browser_state_stale_after'),
        ('browser_state_poll_interval', 'browser_schedule_confirmation_timeout'),
        ('browser_feeding_poll_interval', 'browser_feeding_stale_after'),
        ('pi_request_timeout', 'browser_request_timeout'),
    ):
        if values[interval] >= values[limit]:
            raise ValueError(f'{limit} must exceed {interval}')
    return values


def outputs(values, backend):
    header = 'Generated by tools/sync_timing.py from AWS timing.json; do not edit.'
    python = '# ' + header + '\n' + ''.join(f'{k.upper()} = {v!r}\n' for k, v in values.items())
    javascript = '// ' + header + '\nexport const timing = Object.freeze(' + json.dumps(values, indent=2) + ');\n'
    return {
        ROOT / 'home/admin/smart-enclosure-api/timing_config.py': python,
        backend / 'timing_config.py': python,
        ROOT / 'home/admin/smart-enclosure-frontend/src/timing.js': javascript,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--backend', type=Path, default=ROOT.parent / 'backend')
    parser.add_argument('--check', action='store_true', help='Fail if generated files differ; do not write')
    args = parser.parse_args()
    if not (args.backend / 'sensor_collector.py').is_file():
        parser.error('--backend must point to the Pi source repository')
    values = validate(json.loads(SOURCE.read_text()))
    stale = []
    for path, content in outputs(values, args.backend).items():
        if not path.exists() or path.read_text() != content:
            stale.append(str(path))
            if not args.check:
                path.write_text(content)
    if args.check and stale:
        parser.exit(1, 'Timing files need regeneration:\n' + '\n'.join(stale) + '\n')
    print('Timing configuration validated; ' + ('generated files match.' if args.check else f'updated {len(stale)} files.'))


if __name__ == '__main__':
    main()
